"""Tests for tests/data/gold_non_archean.json and scripts/gold_compare.py.

Three groups, matching Phase 8 of this step:

  integrity      the gold file is internally well-formed and its evidence is
                 real — every citation actually occurs on the page it names.
  independence   the gold labels were not generated by route.py, typeRdd, or
                 scripts/analyze_routing.py — checked structurally, not by
                 trusting the file's own prose claim.
  comparison     scripts/gold_compare.py's output is deterministic and its
                 categorisation is internally consistent with the gold file.

Nothing here asserts that route.py is "right" or "wrong" — see
DISCOVERY.md 8.8 for that discussion. These tests only protect the gold
file's integrity and the comparison's reproducibility.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
GOLD_PATH = REPO_ROOT / "tests" / "data" / "gold_non_archean.json"

sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from archean.corpus import load_corpus  # noqa: E402
from archean.route import KNOWN_MECHANISMS, Verdict, classify  # noqa: E402
from archean.ground import normalize_text  # noqa: E402


@pytest.fixture(scope="module")
def gold() -> dict:
    return json.loads(GOLD_PATH.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def gold_siren(gold) -> str:
    return gold["_about"]["company_selected"]["siren"]


@pytest.fixture(scope="module")
def gold_corpus(gold_siren, challenge_root):
    root = challenge_root / "data" / gold_siren / "actes"
    if not root.is_dir():
        pytest.skip(f"{root} not present in this checkout")
    return load_corpus(root)


@pytest.fixture(scope="module")
def gold_docs_by_id(gold_corpus):
    return {d.doc_id: d for d in gold_corpus.documents}


# ===========================================================================
# integrity
# ===========================================================================


def test_gold_file_is_valid_json(gold):
    assert isinstance(gold, dict)
    assert gold["items"]


def test_gold_file_declares_what_it_is_not(gold):
    blob = " ".join(gold["_about"]["what_this_is_NOT"]).lower()
    assert "not generated by archean.route" in blob
    assert "not generated from typerdd" in blob
    assert "not an answer key" in blob


def test_selected_company_is_not_archean_or_hadean(gold):
    siren = gold["_about"]["company_selected"]["siren"]
    assert siren not in ("480489707", "499979540")


def test_exclusions_are_explicit_and_justified(gold):
    excluded = gold["_about"]["excluded_from_candidacy"]
    assert "499979540" in excluded
    assert "480489707" in excluded
    assert "already inspected" in excluded["499979540"].lower()


def test_every_item_has_the_required_fields(gold):
    required = {
        "item_id", "document_id", "document_short_id", "mechanism",
        "verdict", "rationale", "metadata_label",
    }
    for item in gold["items"]:
        missing = required - item.keys()
        assert not missing, f"{item.get('item_id')} missing {missing}"


def test_mechanisms_match_route_pys_known_mechanisms(gold):
    """The gold schema deliberately uses the SAME 2 mechanisms as route.py
    (not the 4-mechanism sketch in the task prompt) — see DISCOVERY.md 8.8
    for why a constitution/authorization axis would be uncomparable.
    """
    mechanisms = {item["mechanism"] for item in gold["items"]}
    assert mechanisms == set(KNOWN_MECHANISMS)


def test_verdicts_are_valid_route_py_verdicts(gold):
    valid = {v.name for v in Verdict}
    for item in gold["items"]:
        assert item["verdict"] in valid, item["item_id"]


def test_non_silent_verdicts_have_evidence_location(gold):
    """A label without a precise location is not gold, per this step's
    explicit rule: page + line_index/text is mandatory for anything that
    is not SILENT.
    """
    for item in gold["items"]:
        if item["verdict"] == "SILENT":
            continue
        assert item["page"] is not None, f"{item['item_id']}: no page"
        assert item["evidence_text"], f"{item['item_id']}: no evidence_text"


def test_silent_verdicts_have_no_fabricated_evidence(gold):
    """SILENT does not require inventing negative evidence — page and
    evidence_text must be null, not a placeholder.
    """
    for item in gold["items"]:
        if item["verdict"] == "SILENT":
            assert item["page"] is None
            assert item["evidence_text"] is None


def test_item_ids_are_unique(gold):
    ids = [item["item_id"] for item in gold["items"]]
    assert len(ids) == len(set(ids)), "duplicate item_id found"


def test_document_ids_are_24_char_hex(gold):
    for item in gold["items"]:
        doc_id = item["document_id"]
        assert len(doc_id) == 24
        assert all(c in "0123456789abcdef" for c in doc_id)


def test_document_short_id_matches_document_id_suffix(gold):
    for item in gold["items"]:
        assert item["document_id"].endswith(item["document_short_id"]), item["item_id"]


def test_every_document_exists_in_the_corpus(gold, gold_docs_by_id):
    for item in gold["items"]:
        assert item["document_id"] in gold_docs_by_id, (
            f"{item['item_id']}: document {item['document_id']} not found"
        )


def test_every_cited_page_exists_in_its_document(gold, gold_docs_by_id):
    for item in gold["items"]:
        if item["page"] is None:
            continue
        doc = gold_docs_by_id[item["document_id"]]
        assert 1 <= item["page"] <= doc.page_count, (
            f"{item['item_id']}: page {item['page']} out of range for a "
            f"{doc.page_count}-page document"
        )


def test_evidence_text_actually_occurs_on_the_cited_page(gold, gold_docs_by_id):
    """The load-bearing integrity check: every citation must be verifiable
    against the OCR as it exists today, not merely asserted in prose.
    """
    for item in gold["items"]:
        if item["evidence_text"] is None:
            continue
        doc = gold_docs_by_id[item["document_id"]]
        page = doc.page(item["page"])
        assert page.has_ocr, f"{item['item_id']}: page {item['page']} has no OCR"
        data = json.loads(page.ocr_path.read_text(encoding="utf-8"))
        target = normalize_text(item["evidence_text"])
        found = any(
            target in normalize_text(ln.get("text") or "")
            for ln in data.get("ocr") or []
        )
        assert found, (
            f"{item['item_id']}: evidence_text not found on page {item['page']} "
            f"of {item['document_short_id']} — {item['evidence_text']!r}"
        )


def test_line_index_when_given_points_at_the_evidence_text(gold, gold_docs_by_id):
    """Where line_index is recorded (not every item has one — some cite a
    page-level fact without pinning the exact OCR array position), it must
    resolve to the exact cited text.
    """
    for item in gold["items"]:
        if item["line_index"] is None or item["evidence_text"] is None:
            continue
        doc = gold_docs_by_id[item["document_id"]]
        page = doc.page(item["page"])
        data = json.loads(page.ocr_path.read_text(encoding="utf-8"))
        ocr_lines = data.get("ocr") or []
        assert 0 <= item["line_index"] < len(ocr_lines), (
            f"{item['item_id']}: line_index {item['line_index']} out of range"
        )
        actual = normalize_text(ocr_lines[item["line_index"]].get("text") or "")
        expected = normalize_text(item["evidence_text"])
        assert expected in actual, (
            f"{item['item_id']}: line_index {item['line_index']} text "
            f"{actual!r} does not contain {expected!r}"
        )


def test_secondary_evidence_pages_are_in_range(gold, gold_docs_by_id):
    for item in gold["items"]:
        doc = gold_docs_by_id[item["document_id"]]
        for sec in item.get("secondary_evidence") or []:
            assert 1 <= sec["page"] <= doc.page_count, item["item_id"]


def test_known_findings_have_required_fields(gold):
    for finding in gold.get("known_findings", []):
        assert finding["id"]
        assert finding["category"]
        assert finding["description"]


def test_known_finding_ids_referenced_by_items_actually_exist(gold):
    known_ids = {f["id"] for f in gold.get("known_findings", [])}
    for item in gold["items"]:
        ref = item.get("known_finding_id")
        if ref is not None:
            assert ref in known_ids, f"{item['item_id']} references unknown finding {ref!r}"


def test_no_duplicate_document_mechanism_pairs(gold):
    """One gold verdict per (document, mechanism) — not two conflicting ones."""
    seen = set()
    for item in gold["items"]:
        key = (item["document_id"], item["mechanism"])
        assert key not in seen, f"duplicate gold item for {key}"
        seen.add(key)


# ===========================================================================
# independence — the gold labels were not generated by the thing they test
# ===========================================================================


def test_gold_file_is_not_produced_by_a_script_reading_route_py():
    """No import of archean.route inside the gold JSON generation path —
    checked the only way that is actually checkable: the JSON file itself
    contains no Verdict enum reprs, Classification reprs, or anything that
    looks like a serialised route.py object, only plain strings the human
    determination process would produce.
    """
    raw = GOLD_PATH.read_text(encoding="utf-8")
    assert "Verdict.OPERATIVE" not in raw
    assert "Classification(" not in raw
    assert "<Verdict" not in raw


def test_metadata_label_is_recorded_separately_from_verdict(gold):
    """Every item's metadata_label is present as its own field, distinct
    from verdict — the gold schema itself cannot collapse the two even if
    someone tried, because they are different JSON keys with different
    (bool|None) vs (str) types.
    """
    for item in gold["items"]:
        assert "metadata_label" in item
        assert item["metadata_label"] in (True, False, None)
        assert isinstance(item["verdict"], str)


def test_no_typerdd_capital_disagreement_was_silently_resolved(gold):
    """Where metadata_label and verdict disagree in the gold file itself
    (independent of the router), the item's rationale must be present —
    the file cannot assert a verdict that contradicts its own recorded
    metadata_label without explaining why in prose.
    """
    for item in gold["items"]:
        if item["mechanism"] != "capital_amount":
            continue
        meta = item["metadata_label"]
        verdict_says_yes = item["verdict"] in ("OPERATIVE",)
        if meta is True and not verdict_says_yes:
            assert item["rationale"], item["item_id"]
        if meta is False and verdict_says_yes:
            assert item["rationale"], item["item_id"]


# ===========================================================================
# comparison script
# ===========================================================================


def test_gold_compare_runs_without_error(gold_siren):
    proc = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "gold_compare.py")],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=120,
    )
    assert proc.returncode == 0, proc.stderr
    assert "gold items:" in proc.stdout


def test_gold_compare_json_output_is_valid(gold_siren):
    proc = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "gold_compare.py"), "--json"],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=120,
    )
    assert proc.returncode == 0, proc.stderr
    rows = json.loads(proc.stdout)
    assert len(rows) == 14


def test_gold_compare_is_deterministic_across_two_processes():
    def run():
        proc = subprocess.run(
            [sys.executable, str(REPO_ROOT / "scripts" / "gold_compare.py"), "--json"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=120,
        )
        assert proc.returncode == 0
        return proc.stdout

    a, b = run(), run()
    assert a == b


def test_every_disagreement_has_a_category(gold, gold_docs_by_id):
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import gold_compare

    rows = gold_compare.compare(gold, gold_docs_by_id)
    for row in rows:
        if row.get("agree") is False:
            assert row.get("category"), row["item_id"]
            assert row["category"] in gold_compare.CATEGORIES


def test_no_disagreement_is_uncategorized_as_other(gold, gold_docs_by_id):
    """A specific, current-state assertion (not a general guarantee): every
    disagreement in THIS run traces to one of two fully-diagnosed causes.
    If this ever fails, either route.py changed or a new, undiagnosed
    disagreement appeared — investigate before touching this test.
    """
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import gold_compare

    rows = gold_compare.compare(gold, gold_docs_by_id)
    others = [r for r in rows if r.get("category") == "other"]
    assert others == [], f"uncategorized disagreements: {others}"


def test_agreement_and_disagreement_counts_match_measured_state(gold, gold_docs_by_id):
    """The exact counts measured and written into DISCOVERY.md 8.9 after the
    four-digit numeral/year fix: 10 agreements, 4 disagreements (1
    date_problem, 3 mechanism_coverage_gap — share_transfer's known ceiling,
    unaffected by this fix).

    Before the fix (DISCOVERY.md 8.8, superseded): 8 agreements, 6
    disagreements (3 date_problem, 3 mechanism_coverage_gap). Fixing the
    bare-year-as-any-4-digit-numeral bug (8.9) correctly flips 5420's and
    5426's capital_amount items from disagree to agree — both are real,
    realised capital increases and are now classified OPERATIVE, matching
    gold. 5421's capital_amount item stays a disagreement, but its own
    known_findings text already named the second, independent cause: a
    boilerplate line matches TRANSITION_RE+AMOUNT_RE on its own ("...au
    titre de l'augmentation de capital de la" + a nearby amount) and used to
    be accidentally suppressed into RECITAL by the very year-misparse bug
    fixed here. Removing that bug does not remove the boilerplate
    false-match; it only stops hiding it, so the document now surfaces as
    OPERATIVE instead of RECITAL — still a disagreement against gold's
    MENTION, still correctly categorised date_problem because it is the
    same known_finding_id ("date-misparse-share-counts-as-years"), just a
    different downstream verdict of the same root cause.
    """
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import gold_compare
    from collections import Counter

    rows = gold_compare.compare(gold, gold_docs_by_id)
    agree = sum(1 for r in rows if r.get("agree"))
    disagree = sum(1 for r in rows if r.get("agree") is False)
    assert agree == 10
    assert disagree == 4

    cats = Counter(r.get("category") for r in rows if r.get("agree") is False)
    assert cats == Counter({"date_problem": 1, "mechanism_coverage_gap": 3})


def test_the_remaining_date_problem_disagreement_is_5421_capital(gold, gold_docs_by_id):
    """Only one of the original three date_problem items is still a
    disagreement. 5420 and 5426's capital_amount items are fixed (see
    test_5420_and_5426_are_now_correctly_operative below) — they no longer
    appear here. 5421's capital_amount item remains, for the independent,
    pre-documented boilerplate-match reason recorded in this gold item's own
    known_findings entry, not because the year-misparse bug is unfixed.
    """
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    import gold_compare

    rows = gold_compare.compare(gold, gold_docs_by_id)
    date_problem_ids = {r["item_id"] for r in rows if r.get("category") == "date_problem"}
    assert date_problem_ids == {"bockel-5421-capital"}


def test_the_fix_lives_in_frenchnums_context_layer_not_a_route_py_special_case():
    """This step's explicit scope was to fix the bug conservatively, in
    whichever layer's contract was actually wrong — not to make route.py
    special-case JACQUES BOCKEL's numbers to pass this gold set.

    Phase-2 audit conclusion (DISCOVERY.md 8.9): parse_french_year's own
    lexical contract is correct and unchanged — called in isolation on a
    string, it cannot know whether "1766" means a year or a quantity, and
    it is not its job to guess. That is still true:
    """
    from archean.frenchnum import FrenchDateError, parse_french_date_parts, parse_french_year

    assert parse_french_year("1766") == 1766
    assert parse_french_year("2000") == 2000

    # The fix is in the *context-consuming* layer instead: a bare 4-digit
    # numeral with no day, no month and no explicit "l'an" marker is not a
    # date at all, so parse_french_date_parts (not parse_french_year) now
    # refuses it — this is what actually stops route.py's recital check
    # from treating either share count as an earlier year.
    with pytest.raises(FrenchDateError):
        parse_french_date_parts("1766")
    with pytest.raises(FrenchDateError):
        parse_french_date_parts("2000")


# ===========================================================================
# direct route.py behaviour on the gold documents — regression pins
# ===========================================================================


def test_541d_document_level_verdict_still_agrees_despite_the_bug(gold_docs_by_id):
    doc = next(d for d in gold_docs_by_id.values() if d.doc_id.endswith("541d"))
    result = classify(doc, "capital_amount")
    assert result.verdict == Verdict.OPERATIVE


def test_5420_and_5426_are_now_correctly_operative(gold_docs_by_id):
    """Was pinned as a bug (DISCOVERY.md 8.8): 'euros par création de 2000
    parts nouvelles de 75,00 euros' has its share count '2000' misread as a
    year earlier than the 2013 filing, wrongly suppressing the sole
    operative line in each file ('pour le porter de 150 000 euros à 300 000
    euros') into RECITAL.

    Fixed by DISCOVERY.md 8.9: parse_french_date_parts's bare-year fallback
    now requires an explicit "l'an" marker, so a bare "2000" with no day, no
    month and no marker is no longer read as a date at all. Both documents
    correctly reach OPERATIVE, matching gold. Original corpus text and
    document identity kept unchanged from the pinned version — only the
    expected verdict changed, per DISCOVERY.md 8.9.
    """
    for short in ("5420", "5426"):
        doc = next(d for d in gold_docs_by_id.values() if d.doc_id.endswith(short))
        result = classify(doc, "capital_amount")
        assert result.verdict == Verdict.OPERATIVE, (
            f"{short}: expected the fixed behaviour (OPERATIVE); if this "
            f"regressed, check DISCOVERY.md 8.9's bare-year-fallback fix"
        )


def test_share_transfer_never_reaches_operative_on_the_second_company_either(
    gold_docs_by_id,
):
    for doc in gold_docs_by_id.values():
        result = classify(doc, "share_transfer")
        assert result.verdict != Verdict.OPERATIVE
        assert result.verdict != Verdict.RECITAL
